### ISSUE TITLE
Menu in safari iets uit lijn

### ISSUE THREAD

**Issue by jmslbam** [jmslbam/wordcamp-rotterdam-2018-css#10]
@chantalcoolsma heb je screenshot voor me? versie nummer safari?

**Comment by chantalcoolsma** [comment]
Laatste versie: Versie 11.0.3 (13604.5.2)

![schermafbeelding 2017-12-12 om 10 19 30](https://user-images.githubusercontent.com/867632/33878591-2cc5b2f2-df2c-11e7-9810-8ca38f093166.png)

**Comment by jmslbam** [comment]
Done!
